export const radioStations = [
  {
    title: "WCRX Chicago's Underground Radio",
    location: "Chicago (USA)",
    genre: "pop",
    img: "https://i.iheart.com/v3/re/assets.brands/6040110a9538edc2d6937e84?ops=gravity(%22center%22),contain(300,300)&quality=80",
    url: "https://wcrx.streamguys1.com/live",
    id: 1,
  },
  {
    title: "KIIS FM",
    location: "Chicago (USA)",
    genre: "pop",
    img: "",
    url: "https://n1fb-e2.revma.ihrhls.com/zc849?rj-ttl=5&rj-tok=AAABkjpPB4wAJRqhN_juLlkkuw",
    id: 2,
  },
  {
    title: "WBEZ Public Radio",
    location: "Chicago (USA)",
    genre: "pop",
    img: "",
    url: "https://stream.wbez.org/wbez128.mp3",
    id: 3,
  },
  // {
  //   title: "WCRX Chicago's Underground Radio",
  //   location: "Chicago",
  //   genre: "pop",
  //   img: "",
  //   url: "https://wcrx.streamguys1.com/live",
  //   id: 11,
  // },
  // {
  //   title: "KIIS FM",
  //   location: "Chicago",
  //   genre: "pop",
  //   img: "",
  //   url: "https://n1fb-e2.revma.ihrhls.com/zc849?rj-ttl=5&rj-tok=AAABkjpPB4wAJRqhN_juLlkkuw",
  //   id: 21,
  // },
  // {
  //   title: "WBEZ Public Radio",
  //   location: "Chicago",
  //   genre: "pop",
  //   img: "",
  //   url: "https://stream.wbez.org/wbez128.mp3",
  //   id: 31,
  // },
  // {
  //   title: "WCRX Chicago's Underground Radio",
  //   location: "Chicago",
  //   genre: "pop",
  //   img: "",
  //   url: "https://wcrx.streamguys1.com/live",
  //   id: 12,
  // },
  // {
  //   title: "KIIS FM",
  //   location: "Chicago",
  //   genre: "pop",
  //   img: "",
  //   url: "https://n1fb-e2.revma.ihrhls.com/zc849?rj-ttl=5&rj-tok=AAABkjpPB4wAJRqhN_juLlkkuw",
  //   id: 22,
  // },
  // {
  //   title: "WBEZ Public Radio",
  //   location: "Chicago",
  //   genre: "pop",
  //   img: "",
  //   url: "https://stream.wbez.org/wbez128.mp3",
  //   id: 32,
  // },
  // {
  //   title: "WCRX Chicago's Underground Radio",
  //   location: "Chicago",
  //   genre: "pop",
  //   img: "",
  //   url: "https://wcrx.streamguys1.com/live",
  //   id: 121,
  // },
  // {
  //   title: "KIIS FM",
  //   location: "Chicago",
  //   genre: "pop",
  //   img: "",
  //   url: "https://n1fb-e2.revma.ihrhls.com/zc849?rj-ttl=5&rj-tok=AAABkjpPB4wAJRqhN_juLlkkuw",
  //   id: 221,
  // },
  // {
  //   title: "WBEZ Public Radio",
  //   location: "Chicago",
  //   genre: "pop",
  //   img: "",
  //   url: "https://stream.wbez.org/wbez128.mp3",
  //   id: 321,
  // },
];

export const favoriteStations = [
  {
    id: 1,
  },
  {
    id: 2,
  },
  {
    id: 3,
  },
];
